# Nginxサーバの設定ブロック
server {
    ## HTTPの80番ポートでALBやクライアントからのリクエスト待ち受ける（待ち受けポート）
    listen 80;
    ## サーバ名を指定。ワイルドカード「_」は、全てのホスト名とIPアドレスを待ち受ける。
    server_name _;
    
    ## ヘルスチェック用エンドポイント（ヘルスチェック用のhtmlファイルを作成することも可能だが、軽量なJSONレスポンスを返すことも可能）
    location /health {
        ### 軽量なJSONレスポンスを返す
        add_header Content-Type application/json;
        return 200 '{"status":"ok","service":"front-nginx"}';
    }
    
    ## ルートディレクトリへのリクエストを処理するブロック 
    location / {
        ### ルートディレクトリ（ドキュメントルート）を指定
        root /usr/share/nginx/html;
        ### インデックスファイル（デフォルトのファイル名）を指定
        index index.html;
        ### リクエストされたファイルがルートディレクトリに見つからない場合、index.htmlにリダイレクト（404エラーを回避）
        try_files $uri $uri/ /index.html;
    }

    ## APIリクエストをService Connect経由で別タスクのPythonコンテナに転送
    ### 同一ECSクラスター内・異なるサービス名で起動している別タスク間通信を実現
    location /api/ {
        proxy_pass http://${SERVICE_DISCOVERY_NAME}.${NAMESPACE_NAME}.local:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    ## CORS（異なるオリジン間でのリソース共有を制御するための仕組み）ヘッダー設定
    ### クライアントがブラウザ（ユーザー操作）からAPIを叩くため、CORSの記述が必要
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
    add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
}
